### ISSUE TITLE
npm access

### ISSUE THREAD

**Issue by alexander-akait** [css-modules/postcss-icss-selectors#124]
@TrySound friendly ping, we rewrite `css-loader` on `ICSS` spec and move out `css` modules from `css-loader` in favor `postcss-loader` and `postcss-icss-*` plugins. Can you give npm access to fix bugs/update dependencies and improve features. 
Repos: 
- https://github.com/css-modules/postcss-icss-values
- https://github.com/css-modules/postcss-icss-selectors
- https://github.com/css-modules/postcss-icss-composes
- https://github.com/css-modules/postcss-icss-keyframes
- https://github.com/css-modules/generic-names
- https://github.com/css-modules/icss-utils

**Comment by TrySound** [comment]
Done. Except `generic-names` to which I don't have an access.

**Comment by alexander-akait** [comment]
@TrySound thanks! Looks i forgot about:
- https://github.com/css-modules/postcss-icss
- https://github.com/css-modules/postcss-icss-import
- https://github.com/css-modules/postcss-icss-url

We use own plugins for this purpose inside `css-loader`, but maybe can want use `postcss` ICSS without `css-loader`, will be great have permissions to release new version for these guys also

**Comment by TrySound** [comment]
Done

**Comment by alexander-akait** [comment]
@TrySound Thanks!
