### ISSUE TITLE
Move code quality warnings to a linter

### ISSUE THREAD

**Issue by geelen** [css-modules/postcss-icss-selectors#15]
After some discussion, I think we need to drop any kind of "quality judgement" out of this repo and into its own. Merging https://github.com/css-modules/postcss-modules-local-by-default/pull/13 is the first step here.

This will allow us to be more specific in what we're actually checking for, to best help users understand how to make use
- `input {}` — Global tag declaration. Mark this with :global to keep it or consider alternatives http://...
- `.foo input {}` — Potentially deep tag selector. You may be overwriting nested styles.
- `.foo > input {}` — no warning
- `.foo .bar` — Unnecessary nesting of .bar within .foo. .bar is already globally unique

That sort of thing.

**Comment by sokra** [comment]
> .foo .bar — Unnecessary nesting of .bar within .foo. .bar is already globally unique

That should be fine. Classes a unique but this can be used to judge about the structure. i. e.

``` css
.link {
  color: red;
}

.active .link {
  color: green;
}
```

**Comment by geelen** [comment]
With Mark starting https://github.com/css-modules/postcss-modules-lint, I think we can close this and start working directly there
