### ISSUE TITLE
Ignore :export and :import

### ISSUE THREAD

**Issue by geelen** [css-modules/postcss-icss-selectors#3]
Maybe don't treat any bare pseudo-selectors (`:root`,`:host`,`:not`) as local-able? But at least allow `:export` and `:import` to fall through, since there might be plugins ahead of the css modules ones that want to export/import stuff. Or the user might want to simply export a variable by hand for some reason.

**Comment by markdalgleish** [comment]
Could you send a PR with failing tests?
