### ISSUE TITLE
Throws on :global after an operator

### ISSUE THREAD

**Issue by sohkai** [css-modules/postcss-icss-selectors#36]
Trying to use a `:global` rule immediately after a CSS operator (ie. `+`, `~`, `>`) throws an `Missing whitespace before :global` error (which, also actually looks like it should be an "Extra whitespace after :global" error: https://github.com/css-modules/postcss-modules-local-by-default/blob/master/index.js#L26?).

Specifically, I've had it break on me when trying to do things like this: `.class1 > :global .class2`, because the plugin doesn't recognize the `>` as being able to start a new broad rule (the operator leaves `context.lastWasSpacing` off).

From what I can tell, this looks like it was just forgotten about since there's nothing off the top of my head about CSS Modules that would prevent this from working and there are no tests for it. It should be easily fixed by adding a rule for `operator` types that turns `context.lastWasSpacing` on, but I'm quite confused at the whole `context.enforceNoSpacing` situation and how operators would stay consistent with it if we treat them similarly to spacing. Rules like `.class1:local .class2` throw, but are rules like `class1:local.class2` supposed to be allowed (they seem to be)?

Given that we can detect usages of `:global(...)`/`:local(...)` seperately, wouldn't it make more sense to enforce broad `:global`/`:local` usage to always be surrounded by a space or operator?

**Comment by davidrossjones** [comment]
+1

**Comment by TrySound** [comment]
Fixed in https://github.com/css-modules/postcss-modules-local-by-default/commit/c1bcce09f5dc56738f6792acc7c01217b092b8e3

**Comment by jfstephe** [comment]
@TrySound This is great that this has been fixed - many thanks! I'm seeing it using the latest gulp-postcss package, but can't unwind the dependencies to understand what needs to be re-published with new dependencies. Any clues?
