### ISSUE TITLE
How about a `:global { ... }`?

### ISSUE THREAD

**Issue by andywer** [css-modules/postcss-icss-selectors#45]
## Use case

We use a 3rd-party widget that allows us to add a custom CSS class for the widget's root element, but not for its various sub-elements.
## What we have

``` css
.fancy-widget {
  ...

  :global .widget-header {
    ...
  }

  :global .widget-footer {
    ...
  }

  :global .widget-link {
    ...
  }
}
```
## What would help

``` css
.fancy-widget {
  ...

  :global {
    .widget-header {
      ...
    }

    .widget-footer {
      ...
    }

    .widget-link {
      ...
    }
  }
}
```
## Or maybe

``` css
:local .fancy-widget {    /* when setting this to :local explicitly, all child selectors will be global by default */
  ...

  .widget-header {
    ...
  }

  .widget-footer {
    ...
  }

  .widget-link {
    ...
  }
}
```

Changing the plugin configuration is not an option, since we don't want to global-by-default our other CSS files.

Any suggestions what would be the preferrable way? Maybe we will implement the feature ourselves and open a PR.

**Comment by tivac** [comment]
Would [`postcss-nested`](https://github.com/postcss/postcss-nested) help with this?

**Comment by andywer** [comment]
@tivac You mean for the `:global { ... }`? The problem is that as far as I can see there is no `:global { ... }` yet... ;)

**Comment by tivac** [comment]
@andywer Yeah, IIRC if you used `postcss-nested` it will apply the `:global` prefix to all the child rules.

So

``` css
:global {
    .widget-header {
      ...
    }

    .widget-footer {
      ...
    }

    .widget-link {
      ...
    }
  }
```

becomes

``` css
:global .widget-header {
  ...
}

:global .widget-footer {
  ...
}

:global .widget-link {
  ...
}
```

which looks like what you need? Huge caveat, haven't actually tested that out personally so apologies if I'm full of it.

**Comment by andywer** [comment]
Ahh yeah, right. That should work :)

Thanks a lot!

(Will close the ticket in great confidence)

**Comment by andywer** [comment]
Unfortunately that did not work out... :-/

The problem is that our rules are more complex, like:

``` css
.fancy {
  > :global(.foo) {
    color: red;
  }
}
```

So there seems to be no way to do `:global { .foo { color: red; } }` and let postcss-nested do the magic.

I still think that a `:global { ... }` that is recognized by postcss-modules-local-by-default and that disables localizing of the child selectors might be the cleanest solution.

**Comment by andywer** [comment]
No, I was wrong. It's all fine now.

If someone else is interested:

``` css
.fancy:global(.widget) {
  :global .foo {
    .bar {
      color: red;
    }
  }
}
```

compiles properly to

``` css
._localized_class_name-fancy.widget .foo .bar {
  color: red;
}
```

Thanks for your time, @tivac!
