### ISSUE TITLE
problem requiring "foundation" as global with sass

### ISSUE THREAD

**Issue by cristiancedenogallego** [css-modules/postcss-icss-selectors#62]
Inconsistent rule global/local result in rule ".row.medium-unstack > .column, :global .row.medium-unstack > .columns"
   (multiple selectors must result in the same mode for the rule)

**Comment by tnguven** [comment]
Same issue with webpack :(

ERROR in ./~/css-loader?modules&importLoaders=2&localIdentName=[name]--[local]--[hash:base64:5]&sourceMap!./~/postcss-loader!./~/sass-loader?outputStyle=expanded&sourceMap!./app/styles/core.scss
Module build failed: Inconsistent rule global/local result in rule ".row.medium-unstack > .column, :global .row.medium-unstack > .columns" (multiple selectors must result in the same mode for the rule) (242:8)
