### ISSUE TITLE
Is it possible to have a source map?

### ISSUE THREAD

**Issue by mattmischuk** [css-modules/postcss-icss-selectors#69]
Is it possible to have a source map to the original un-tokenized string?

**Comment by TrySound** [comment]
Do you mean source map for selectors?

**Comment by mattmischuk** [comment]
Yes, debugging is difficult currently.

**Comment by TrySound** [comment]
Well, for this you need just use descriptive name generation.

/cc @ai @ben-eb

**Comment by TrySound** [comment]
Okay. It's depends on browser mostly. I guess source maps are produces in mapped code. But browser will show generated (functional) selectors in debugger and source maps won't help even if it would be possible.

**Comment by mattmischuk** [comment]
Thanks for looking into this. :)
