### ISSUE TITLE
Add installation / usage docs

### ISSUE THREAD

**Issue by necolas** [css-modules/postcss-icss-selectors#8]
:)

**Comment by geelen** [comment]
Hey @necolas, sorry, I wasn't checking these issues regularly yet. This is sorta not the visible package, but we should point people at the installable pieces (https://github.com/css-modules/jspm-demo, https://github.com/css-modules/webpack-demo and https://github.com/css-modules/css-modulesify) from the readme, so I'll close this when we've done that :)

**Comment by necolas** [comment]
Well it's an installable module that other tools rely on, so if I were to be writing a tool it might be useful for this module to be documented.

**Comment by keske** [comment]
Hi guys, I absolute agree with Necolas it would be great to see any docs for this module.

I trying this way:

```Javascript
new webpack.LoaderOptionsPlugin({
      options: {
        postcss: [
          require('postcss-modules-local-by-default'),
          ...,
        ],
      },
}),
```

And this doesn't works.

Thanks!
